name: .NET
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Install dotnet ef
      run: dotnet tool install --global dotnet-ef
    - name: Build with dotnet
      run: dotnet build --configuration Release CleanArchitecture.sln

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: tool restore
      run: dotnet tool restore
    - name: run tests
      run: dotnet test CleanArchitecture.sln --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:ExcludeByFile=\"tests/*.cs,**/Migrations/*.cs,src/WebUI/Program.cs,src/WebUI/Startup.cs\"
    - name: publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: dotnet reportgenerator "-reports:tests/**/coverage.cobertura.xml" "-targetdir:.coverage-report" -reporttypes:cobertura
        coverageLocations: |
          ${{github.workspace}}/.coverage-report/Cobertura.xml:cobertura